# Generated by Django 3.2.10 on 2022-01-22 03:14

from django.db import migrations, models
import donor.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorCard',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cardImage', models.ImageField(blank=True, null=True, upload_to=donor.models.upload_path)),
                ('donorDate', models.DateField()),
                ('donorType', models.CharField(max_length=10)),
                ('donorVolume', models.IntegerField()),
                ('donorName', models.CharField(max_length=10)),
                ('donorBirth', models.DateField()),
                ('donorPlace', models.CharField(max_length=10)),
                ('cardId', models.CharField(max_length=10)),
            ],
        ),
    ]
