# Generated by Django 3.2.10 on 2022-01-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_donorcard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorcard',
            name='cardId',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
