# Generated by Django 3.2.11 on 2022-01-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_authtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='private_key',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
